// data.js — بيانات وهمية (Mock Data) لفعاليات المنطقة الشرقية
// لاحقًا يمكن استبدال هذا الملف بطلب حقيقي من API بنفس البنية

const events = [
  {
    id: 1,
    name: "مهرجان الظهران للثقافة",
    name_en: "Dhahran Culture Festival",
    category: "ثقافي",
    city: "الظهران",
    city_en: "Dhahran",
    lat: 26.2994,
    lng: 50.1072,
    venue: "مركز الملك عبدالعزيز الثقافي",
    venue_en: "King Abdulaziz Center for World Culture",
    date: "2026-09-15",
    time: "18:00 - 23:00",
    description: "مهرجان سنوي يحتفل بالتراث الثقافي للمنطقة الشرقية",
    description_en: "An annual festival celebrating the cultural heritage of the Eastern Province",
    vibe: ["تراثي", "عائلي", "ثقافي"],
    price: 60,
    seatsAvailable: 80,
  },
  {
    id: 2,
    name: "مهرجان الدمام للتسوق",
    name_en: "Dammam Shopping Festival",
    category: "تسوق",
    city: "الدمام",
    city_en: "Dammam",
    lat: 26.4127,
    lng: 50.0978,
    venue: "مجمع الظهران مول",
    venue_en: "Dhahran Mall Complex",
    date: "2026-09-20",
    time: "10:00 - 22:00",
    description: "أكبر مهرجان تسوق في المنطقة الشرقية مع خصومات وعروض",
    description_en: "The Eastern Province's biggest shopping festival, with discounts and deals",
    vibe: ["تسوق", "عائلي", "ترفيهي"],
    price: 0,
    seatsAvailable: 500,
  },
  {
    id: 3,
    name: "مهرجان الجبيل للفنون",
    name_en: "Jubail Arts Festival",
    category: "فنون",
    city: "الجبيل",
    city_en: "Jubail",
    lat: 27.0106,
    lng: 49.671,
    venue: "مركز الجبيل للفنون",
    venue_en: "Jubail Arts Center",
    date: "2026-10-01",
    time: "17:00 - 21:00",
    description: "معرض فني يضم أعمال فنانين محليين وعالميين",
    description_en: "An art exhibition featuring works by local and international artists",
    vibe: ["فني", "ثقافي", "إبداعي"],
    price: 40,
    seatsAvailable: 45,
  },
  {
    id: 4,
    name: "مهرجان الخبر للسياحة",
    name_en: "Khobar Tourism Festival",
    category: "سياحة",
    city: "الخبر",
    city_en: "Khobar",
    lat: 26.2072,
    lng: 50.1921,
    venue: "الكورنيش الشمالي",
    venue_en: "North Corniche",
    date: "2026-10-10",
    time: "16:00 - 23:00",
    description: "مهرجان سياحي على واجهة الخبر البحرية مع فعاليات متنوعة",
    description_en: "A tourism festival on Khobar's waterfront with a variety of activities",
    vibe: ["سياحي", "عائلي", "ترفيهي"],
    price: 75,
    seatsAvailable: 200,
  },
  {
    id: 5,
    name: "مهرجان القطيف للتراث",
    name_en: "Qatif Heritage Festival",
    category: "تراثي",
    city: "القطيف",
    city_en: "Qatif",
    lat: 26.5275,
    lng: 49.9915,
    venue: "سوق القطيف القديم",
    venue_en: "Old Qatif Souq",
    date: "2026-10-15",
    time: "18:00 - 22:00",
    description: "مهرجان يحتفل بالتراث والتاريخ الغني لمحافظة القطيف",
    description_en: "A festival celebrating the rich heritage and history of Qatif Governorate",
    vibe: ["تراثي", "تاريخي", "عائلي"],
    price: 35,
    seatsAvailable: 60,
  },
  {
    id: 6,
    name: "مهرجان الظهران التقني",
    name_en: "Dhahran Tech Festival",
    category: "تقني",
    city: "الظهران",
    city_en: "Dhahran",
    lat: 26.2834,
    lng: 50.1232,
    venue: "مدينة الملك عبدالعزيز للعلوم والتقنية",
    venue_en: "King Abdulaziz City for Science and Technology",
    date: "2026-11-01",
    time: "09:00 - 17:00",
    description: "مؤتمر تقني يضم ورش عمل ومعارض عن أحدث التقنيات",
    description_en: "A tech conference featuring workshops and exhibitions on the latest technologies",
    vibe: ["تقني", "تعليمي", "ابتكار"],
    price: 120,
    seatsAvailable: 150,
  },
  {
    id: 7,
    name: "مهرجان الدمام الموسيقي",
    name_en: "Dammam Music Festival",
    category: "موسيقى",
    city: "الدمام",
    city_en: "Dammam",
    lat: 26.4297,
    lng: 50.0808,
    venue: "مسرح الدمام",
    venue_en: "Dammam Theatre",
    date: "2026-11-10",
    time: "20:00 - 01:00",
    description: "حفل موسيقي يضم أشهر الفرق المحلية والعربية",
    description_en: "A concert featuring some of the most popular local and Arab bands",
    vibe: ["موسيقي", "ترفيهي", "شبابي"],
    price: 150,
    seatsAvailable: 300,
  },
  {
    id: 8,
    name: "معرض الجبيل للكتاب",
    name_en: "Jubail Book Fair",
    category: "ثقافي",
    city: "الجبيل",
    city_en: "Jubail",
    lat: 26.9956,
    lng: 49.667,
    venue: "مركز المعارض بالجبيل",
    venue_en: "Jubail Exhibition Center",
    date: "2026-11-20",
    time: "09:00 - 21:00",
    description: "معرض كتاب يضم دور نشر ومكتبات من جميع أنحاء المملكة",
    description_en: "A book fair featuring publishers and bookstores from across the Kingdom",
    vibe: ["ثقافي", "تعليمي", "عائلي"],
    price: 0,
    seatsAvailable: 400,
  },
  {
    id: 9,
    name: "سباق الخيل بالظهران",
    name_en: "Dhahran Horse Race",
    category: "رياضي",
    city: "الظهران",
    city_en: "Dhahran",
    lat: 26.2934,
    lng: 50.1022,
    venue: "ميدان الظهران للفروسية",
    venue_en: "Dhahran Equestrian Field",
    date: "2026-12-01",
    time: "15:00 - 19:00",
    description: "سباق خيل سنوي يضم أفضل الخيول العربية الأصيلة",
    description_en: "An annual horse race featuring the finest purebred Arabian horses",
    vibe: ["رياضي", "تراثي", "عائلي"],
    price: 90,
    seatsAvailable: 70,
  },
  {
    id: 10,
    name: "مهرجان الخبر للتسوق والترفيه",
    name_en: "Khobar Shopping & Entertainment Festival",
    category: "ترفيهي",
    city: "الخبر",
    city_en: "Khobar",
    lat: 26.2102,
    lng: 50.1881,
    venue: "مجمع الراشد مول",
    venue_en: "Al Rashid Mall",
    date: "2026-12-15",
    time: "10:00 - 23:00",
    description: "مهرجان يضم عروض ترفيهية ومسابقات وتخفيضات كبيرة",
    description_en: "A festival featuring entertainment shows, competitions, and major discounts",
    vibe: ["ترفيهي", "عائلي", "تسوق"],
    price: 50,
    seatsAvailable: 250,
  },
  {
    id: 11,
    name: "مهرجان الأحساء الزراعي",
    name_en: "Al-Ahsa Agricultural Festival",
    category: "تراثي",
    city: "الأحساء",
    city_en: "Al-Ahsa",
    lat: 25.3906,
    lng: 49.5996,
    venue: "واحة الأحساء",
    venue_en: "Al-Ahsa Oasis",
    date: "2026-09-25",
    time: "16:00 - 21:00",
    description: "مهرجان يحتفي بالتنوع الزراعي والنخيل في واحة الأحساء التراثية",
    description_en: "A festival celebrating the agricultural diversity and palm groves of the historic Al-Ahsa oasis",
    vibe: ["تراثي", "زراعي", "عائلي"],
    price: 20,
    seatsAvailable: 300,
  },
  {
    id: 12,
    name: "معرض الدمام للسيارات الكلاسيكية",
    name_en: "Dammam Classic Car Show",
    category: "فنون",
    city: "الدمام",
    city_en: "Dammam",
    lat: 26.4157,
    lng: 50.0968,
    venue: "واجهة الدمام البحرية",
    venue_en: "Dammam Waterfront",
    date: "2026-09-28",
    time: "15:00 - 22:00",
    description: "معرض يستعرض سيارات كلاسيكية نادرة على واجهة الدمام البحرية",
    description_en: "An exhibition showcasing rare classic cars on the Dammam waterfront",
    vibe: ["فني", "ترفيهي"],
    price: 0,
    seatsAvailable: 600,
  },
  {
    id: 13,
    name: "بطولة الجبيل لكرة القدم الشاطئية",
    name_en: "Jubail Beach Football Championship",
    category: "رياضي",
    city: "الجبيل",
    city_en: "Jubail",
    lat: 27.0106,
    lng: 49.653,
    venue: "شاطئ الجبيل",
    venue_en: "Jubail Beach",
    date: "2026-10-05",
    time: "16:00 - 20:00",
    description: "بطولة شاطئية تجمع فرقًا محلية من أنحاء المنطقة الشرقية",
    description_en: "A beach football tournament bringing together local teams from across the Eastern Province",
    vibe: ["رياضي", "شبابي", "عائلي"],
    price: 0,
    seatsAvailable: 400,
  },
  {
    id: 14,
    name: "مهرجان الخبر لليخوت",
    name_en: "Khobar Yacht Festival",
    category: "سياحة",
    city: "الخبر",
    city_en: "Khobar",
    lat: 26.2092,
    lng: 50.1911,
    venue: "مرسى الخبر",
    venue_en: "Khobar Marina",
    date: "2026-10-08",
    time: "17:00 - 23:00",
    description: "فعالية بحرية تعرض يخوتًا فاخرة وجولات بحرية على واجهة الخبر",
    description_en: "A maritime event featuring luxury yachts and boat tours along Khobar's waterfront",
    vibe: ["سياحي", "ترفيهي", "فاخر"],
    price: 100,
    seatsAvailable: 150,
  },
  {
    id: 15,
    name: "سوق القطيف الليلي",
    name_en: "Qatif Night Market",
    category: "تسوق",
    city: "القطيف",
    city_en: "Qatif",
    lat: 26.5295,
    lng: 49.9895,
    venue: "كورنيش القطيف",
    venue_en: "Qatif Corniche",
    date: "2026-10-12",
    time: "18:00 - 00:00",
    description: "سوق ليلي يجمع بائعين محليين ومنتجات تراثية وحرفية",
    description_en: "A night market bringing together local vendors, heritage products, and handicrafts",
    vibe: ["تسوق", "عائلي", "تراثي"],
    price: 0,
    seatsAvailable: 800,
  },
  {
    id: 16,
    name: "ملتقى الظهران للريادة",
    name_en: "Dhahran Entrepreneurship Forum",
    category: "تقني",
    city: "الظهران",
    city_en: "Dhahran",
    lat: 26.2834,
    lng: 50.1052,
    venue: "واحة ظهران التقنية",
    venue_en: "Dhahran Techno Valley",
    date: "2026-10-18",
    time: "09:00 - 16:00",
    description: "ملتقى لرواد الأعمال والشركات الناشئة في قطاع التقنية",
    description_en: "A forum for entrepreneurs and startups in the tech sector",
    vibe: ["تقني", "تعليمي", "ابتكار"],
    price: 0,
    seatsAvailable: 250,
  },
  {
    id: 17,
    name: "مهرجان رأس تنورة البحري",
    name_en: "Ras Tanura Sea Festival",
    category: "سياحة",
    city: "رأس تنورة",
    city_en: "Ras Tanura",
    lat: 26.6481,
    lng: 50.1805,
    venue: "كورنيش رأس تنورة",
    venue_en: "Ras Tanura Corniche",
    date: "2026-10-22",
    time: "16:00 - 22:00",
    description: "فعاليات بحرية وعائلية على أحد أجمل كورنيشات المنطقة الشرقية",
    description_en: "Family and maritime activities on one of the Eastern Province's most beautiful corniches",
    vibe: ["سياحي", "عائلي", "بحري"],
    price: 30,
    seatsAvailable: 350,
  },
  {
    id: 18,
    name: "أمسية شعرية بالأحساء",
    name_en: "Al-Ahsa Poetry Evening",
    category: "ثقافي",
    city: "الأحساء",
    city_en: "Al-Ahsa",
    lat: 25.3736,
    lng: 49.6006,
    venue: "مركز الأحساء الثقافي",
    venue_en: "Al-Ahsa Cultural Center",
    date: "2026-10-27",
    time: "19:00 - 22:00",
    description: "أمسية شعرية تجمع شعراء من المنطقة الشرقية",
    description_en: "A poetry evening bringing together poets from the Eastern Province",
    vibe: ["ثقافي", "أدبي"],
    price: 0,
    seatsAvailable: 120,
  },
  {
    id: 19,
    name: "مهرجان الدمام لعربات الطعام",
    name_en: "Dammam Food Truck Festival",
    category: "ترفيهي",
    city: "الدمام",
    city_en: "Dammam",
    lat: 26.4277,
    lng: 50.0798,
    venue: "حديقة الملك فهد",
    venue_en: "King Fahd Park",
    date: "2026-11-03",
    time: "17:00 - 23:00",
    description: "تجمع لأشهر عربات الطعام المحلية والعالمية بأجواء عائلية",
    description_en: "A gathering of the finest local and international food trucks in a family-friendly atmosphere",
    vibe: ["طعام", "عائلي", "ترفيهي"],
    price: 0,
    seatsAvailable: 700,
  },
  {
    id: 20,
    name: "حفل موسيقي بالخبر",
    name_en: "Khobar Concert",
    category: "موسيقى",
    city: "الخبر",
    city_en: "Khobar",
    lat: 26.2072,
    lng: 50.2021,
    venue: "مسرح الأمير فيصل بن فهد",
    venue_en: "Prince Faisal bin Fahd Theatre",
    date: "2026-11-08",
    time: "20:00 - 23:30",
    description: "حفل موسيقي يجمع فنانين شباب من المملكة",
    description_en: "A concert bringing together young artists from across the Kingdom",
    vibe: ["موسيقي", "شبابي", "ترفيهي"],
    price: 180,
    seatsAvailable: 200,
  },
  {
    id: 21,
    name: "معرض الجبيل الصناعي",
    name_en: "Jubail Industrial Expo",
    category: "تقني",
    city: "الجبيل",
    city_en: "Jubail",
    lat: 27.0106,
    lng: 49.668,
    venue: "مركز معارض الجبيل",
    venue_en: "Jubail Exhibition Center",
    date: "2026-11-15",
    time: "09:00 - 18:00",
    description: "معرض يستعرض أحدث تقنيات الصناعة والطاقة بالمنطقة الشرقية",
    description_en: "An exhibition showcasing the latest industry and energy technologies in the Eastern Province",
    vibe: ["تقني", "تعليمي"],
    price: 0,
    seatsAvailable: 500,
  },
  {
    id: 22,
    name: "مهرجان القطيف التراثي الكبير",
    name_en: "Qatif Grand Heritage Festival",
    category: "تراثي",
    city: "القطيف",
    city_en: "Qatif",
    lat: 26.5135,
    lng: 49.9755,
    venue: "سوق الخميس",
    venue_en: "Al Khamis Souq",
    date: "2026-11-25",
    time: "16:00 - 22:00",
    description: "مهرجان سنوي كبير يحتفل بتراث وتاريخ محافظة القطيف",
    description_en: "A major annual festival celebrating the heritage and history of Qatif Governorate",
    vibe: ["تراثي", "تاريخي", "عائلي"],
    price: 15,
    seatsAvailable: 450,
  }
];
